# Generated by Django 5.2.13 on 2026-09-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingcountdown",
            name="kind",
            field=models.CharField(
                choices=[
                    ("meeting", "Next meeting"),
                    ("anniversary", "Anniversary"),
                    ("birthday", "Birthday"),
                    ("trip", "Trip"),
                    ("other", "Other"),
                ],
                default="meeting",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="virtualdate",
            name="detail",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="virtualdate",
            name="type",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("dinner", "Dinner"),
                    ("gaming", "Gaming"),
                    ("coffee", "Coffee"),
                    ("music", "Music"),
                    ("quiz", "Quiz"),
                    ("talk", "Just talk"),
                    ("surprise", "Surprise"),
                    ("walk", "Walk"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
    ]
