# Generated by Django 5.2.13 on 2026-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_question_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mascot",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("joyful", "Happy"),
                    ("loving", "In love"),
                    ("missing", "Missing you"),
                    ("anxious", "Anxious"),
                    ("sleepy", "Tired"),
                    ("angry", "Upset"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
