# Generated by Django 5.2.13 on 2026-09-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_latitude_user_longitude_user_mood_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=16)),
                ("question_text", models.CharField(max_length=500)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.couple"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dailyquestion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("couple", "question"),
                        name="one_question_choice_per_couple_day",
                    )
                ],
            },
        ),
    ]
