# Generated by Django 5.2.13 on 2026-09-28 21:01

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_dailyquestionchoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlistitem",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="report",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="report_photo",
            field=models.ImageField(
                blank=True, upload_to=core.models.relationship_media_path
            ),
        ),
        migrations.CreateModel(
            name="ImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("date", models.DateField()),
                ("yearly", models.BooleanField(default=True)),
                ("remind_days", models.PositiveSmallIntegerField(default=1)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.couple"
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("apart", "Apart"), ("together", "Together")],
                        max_length=8,
                    ),
                ),
                ("started_on", models.DateField()),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "couple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.couple"
                    ),
                ),
            ],
            options={
                "ordering": ["started_on", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_on", None)),
                        fields=("couple",),
                        name="one_active_mode",
                    )
                ],
            },
        ),
    ]
