# Generated by Django 5.2.13 on 2026-09-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_refresh_unanswered_prompts"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoredMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("data", models.BinaryField()),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
